# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

### Numpy vs Lists 

In [ ]:
# intialise a list with the following elements: 1, 2, 3, 4, 5


# try to multiply 2.5 directly to the created list



Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [ ]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np


In [6]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array

np_l = np.array([1,4,3])

In [5]:
# Multiply each element with 2.5 

np_l*2.5

array([ 2.5, 10. ,  7.5])

In [8]:
# Print the result using the print command. Compare the structure of list and array.
print(np_l*2.5)

[ 2.5 10.   7.5]


In [10]:
# Create a 1-D array using with the elements (1, abc, True)
np_a=np.array([1, 'abc', True])
print(np_a)

['1' 'abc' 'True']


You can see above that the elements are of single data type. The numerical and the boolean value is converted to string. 

### Operations over Arrays
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [14]:
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
list1 = [1,2,3]
list2 = [4,5,6]

# Use the '+' operator and print the results
list3=list1+list2
print(list3)
#+ operator concatenates 2 lists

[1, 2, 3, 4, 5, 6]


In [15]:
# Convert the above lists to arrays and use the '+' operator

np_1 = np.array([1,2,3])
np_2 = np.array([4,5,6])
np_3= np_1+np_2
print(np_3)
# + operator in numpy adds the two

[5 7 9]


You can look at the difference between the two outputs. We will look at different operations over NumPy arrays in detail in the coming segments.

In [ ]:
#creating arrays

a=np.array([1,2,3]) # One dimensional array
b=np.array([(1,2,3),(4,5,6)]) # Two dimensional array
c=np.zeros(3) # 1D array of length 3 all values 0
d=np.ones((3,4)) # 3x4 array with all values 1
e=np.eye(5) # 5x5 array of 0 with 1 on diagonal (Identity matrix)
f=np.linspace(0,100,6) # Array of 6 evenly divided values from 0 to 100
g=np.arange(0,10,3) # Array of values from 0 to less than 10 with step 3 (eg [0,3,6,9])
h=np.full((2,3),8) # 2x3 array with all values 8
i=np.random.rand(4,5) # 4x5 array of random floats between 0-1
j=np.random.rand(6,7)*100 # 6x7 array of random floats between 0-100
k=np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0-4

print(j)